version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    restart: unless-stopped
  postgres:
    image: postgres:17-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=chay-123-al-456
      - POSTGRES_USER=admin
      - POSTGRES_DB=chayal