version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=matzpen-123-mefaked-456
      - POSTGRES_USER=admin
      - POSTGRES_DB=matzpen_mefaked