{{
    const local = 'http://localhost:3000';
    const dev = 'https://commando-server.vercel.app';

    exports.baseUrl = local;
    exports.headers = {
        'Content-Type': 'application/json',
        'static-token': '3650244b-61fc-4f75-95eb-359d7483ff70',
        // 'requestusername': 's9336069',
        // 'is-bi': true
    };

    exports.workspaceId = 41;
}}